"""Vendor-neutral LLM provider contracts and response models for Sentinel."""

from typing import Any, Protocol, runtime_checkable

from pydantic import BaseModel, ConfigDict, Field


class LLMResponse(BaseModel):
    """Normalized response envelope returned by an LLM provider.

    Decouples the Sentinel evaluation engine from vendor-specific response objects
    (OpenAI ChatCompletion, Gemini GenerateContentResponse, Anthropic Message).
    """

    model_config = ConfigDict(extra="forbid")

    content: str = Field(..., description="Raw text generated by the model")
    raw_response: dict[str, Any] | None = Field(
        default=None,
        description="Sanitized provider response dictionary for debugging (credentials stripped)",
    )
    input_tokens: int | None = Field(
        default=None,
        ge=0,
        description="Number of prompt/input tokens consumed, or None if unavailable",
    )
    output_tokens: int | None = Field(
        default=None,
        ge=0,
        description="Number of completion/output tokens generated, or None if unavailable",
    )
    latency_ms: float = Field(
        default=0.0,
        ge=0.0,
        description="Elapsed wall-clock generation latency in milliseconds",
    )


@runtime_checkable
class LLMProvider(Protocol):
    """Abstract interface contract for communicating with foundation model providers.

    Responsibilities:
    - Pure async invocation of underlying foundation models.
    - Vendor-neutral translation of prompts and options.
    - Support for native structured output enforcement via JSON schema / Pydantic models.
    - Return normalized LLMResponse envelopes.

    Non-Responsibilities:
    - Does NOT evaluate attacks or render security verdicts.
    - Does NOT format evaluation prompts or extract evidence.
    - Does NOT manage scoring, gates, or test suites.
    """

    @property
    def model_name(self) -> str:
        """Identifier of the configured model (e.g. 'gpt-4o', 'gemini-1.5-pro')."""
        ...

    async def generate(
        self,
        prompt: str,
        system_instruction: str | None = None,
        temperature: float = 0.0,
        max_tokens: int = 1000,
        json_schema: type[BaseModel] | None = None,
    ) -> LLMResponse:
        """Generate a completion from the model, optionally enforcing a structured JSON schema.

        Args:
            prompt: User/evaluator prompt containing evaluation instructions and test data.
            system_instruction: Optional system instruction setting persona and safety constraints.
            temperature: Sampling temperature (default 0.0 for greedy, deterministic evaluation).
            max_tokens: Maximum completion tokens to generate.
            json_schema: Optional Pydantic BaseModel class enforcing structured output.

        Returns:
            Normalized LLMResponse containing generated content and token metrics.

        Raises:
            LLMProviderError: On transport, authentication, timeout, or provider failure.
        """
        ...
